workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        APP_STORE_CONNECT_API_KEY_ID: VM33JVN765  # API Key ID
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: 2b87fc77-2aad-4934-8e80-12db199796b7  # API Key Issuer ID
        APP_STORE_CONNECT_PRIVATE_KEY: |
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjn7XdHBVryTY5mLe
          3XeVYTv6YfVhUUD62ycHf0Xe7oegCgYIKoZIzj0DAQehRANCAARU6WWeYwT+9tbV
          No/s2UOS0iiGXjph1YbF9mQ2bvbJpH4AvE1Z9PHDFr2dmMW+zUlcJSPe/m2F2ajw
          tcqgmeMB  # Private Key
    scripts:
      - name: Build iOS
        script: |
          flutter --version
          flutter clean
          flutter pub get
          flutter upgrade
          sudo gem install cocoapods
          pod repo update
          cd ios
          pod install
          flutter build ios --release --no-codesign  # Kod imzalama yapmadan iOS uygulaması oluşturur
          flutter build ios --simulator
    artifacts:
      - build/ios/ipa/*.ipa  # IPA dosyasını çıktı olarak alır
    integrations:
      app_store_connect: tsb  # Apple App Store Connect entegrasyonu
    publishing:
      app_store_connect:
        auth: integration  # Entegrasyon ile kimlik doğrulama
        submit_to_testflight: true  # TestFlight'a yükler
