workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        APP_STORE_CONNECT_API_KEY_ID: CCKZZW6UYU # API Key ID
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: 2b87fc77-2aad-4934-8e80-12db199796b7 # API Key Issuer ID
        APP_STORE_CONNECT_PRIVATE_KEY: |
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggfFcZI50Q7rzSo+S
          8oEGxkBoCRWNHshyQ3mJVLcNnwSgCgYIKoZIzj0DAQehRANCAAT1JEMM/YHu03Lx
          FY5iTlgtYEqePpTtMiEZUqxO7nZUjRX7/OLO0YOUBW/UofWk2y4WFolUnSQ33LJW
          3ThDHhhp
    scripts:
      - name: Build iOS
        script: |
          flutter pub get
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: turkiyesporbilimleri.com@turkiyesporbilimleri.com # Apple Kimliği
        app_specific_password: fxfn-hsgq-nppn-tbuy # Uygulamaya özel parola
        submit_to_testflight: true
