workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
    scripts:
      - name: Flutter bağımlılıklarını yükle
        script: |
          cd C:/Users/zisan/OneDrive/Masaüstü/GitHub/newbesyo  # Projenizin bulunduğu dizine git
          flutter pub get
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: turkiyesporbilimleri.com@turkiyesporbilimleri.com # Apple Kimliği
        app_specific_password: tsbbes # Uygulamaya özel parola
        api_key_id: CCKZZW6UYU
        api_key_issuer_id: 2b87fc77-2aad-4934-8e80-12db199796b7
        api_key_file: "C:\\Users\\zisan\\Downloads\\AuthKey_CCKZZW6UYU.p8" # API key dosyasının yolu
        submit_to_testflight: true
    cache:
      paths:
        - C:\\Users\\zisan\\.pub-cache
        - C:\\Users\\zisan\\Library\\Caches\\CocoaPods
        - C:\\Users\\zisan\\.cocoapods\\repos
