name: besyocity
description: A new Flutter project for BESYOcity.
version: 1.0.0+15

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.0.0
  url_launcher: ^6.0.0
  google_fonts: ^6.2.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  logging: ^1.3.0
  intl: ^0.20.1
  firebase_messaging: ^15.1.5
  firebase_analytics: ^11.3.6
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  video_player: ^2.9.2
  webview_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 900

  assets:
    - assets/images/besyo_logo.png
    - assets/images/birinciay.png
    - assets/images/ikinciay.png
    - assets/images/ucuncuay.png
    - assets/images/dorduncuay.png
    - assets/images/1ay.png
    - assets/images/2ay.png
    - assets/images/3ay.png
    - assets/images/4ay.png
    - assets/images/5ay.png
    - assets/images/6ay.png
    - assets/images/7ay.png
    - assets/images/8ay.png
    - assets/images/9ay.png
    - assets/images/10ay.png
    - assets/images/11ay.png
    - assets/images/tsb.jpeg
    - assets/images/kitap1.jpeg
    - assets/images/kitap2.jpeg
    - assets/images/sl1.png
    - assets/images/sl2.png
    - assets/images/sl3.png
    - assets/images/sl4.png
    - assets/images/top.jpeg
    - assets/images/seat.jpeg
    - assets/images/ayakkabi.jpeg
    - assets/images/tshirt.jpeg
    - assets/images/corap.jpeg
    - assets/images/cceket.jpeg
    - assets/images/video1.mp4
    - assets/images/video2.mp4
    - assets/images/parkur.jpg
    - assets/images/besyo.jpg
    - assets/images/test.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  round_icon: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/tsb.jpeg
  android: true
  ios: true
  web: true
